[package]
name = "zeroflight"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-semihosting = "0.5.0"
defmt = "0.3.10"
panic-probe = { version = "0.3.2", features = ["defmt"] }
panic-semihosting = { version = "0.6.0", features = ["exit"] }
rtic = { version = "2.1.2", features = ["thumbv7-backend"] }
stm32f4xx-hal = { version = "0.22.1", features = ["stm32f405"] }
