[package]
name = "zeroflight"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
defmt = "0.3.10"
defmt-rtt = "0.4.1"
panic-halt = "1.0.0"
rtic = { version = "2.1.2", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "2.0.3", features = ["cortex-m-systick"] }
stm32f1xx-hal = { version = "0.10.0", features = ["stm32f103"] }
usb-device = "0.2.8"
usbd-serial = "0.1.1"
